server:
  port: 9191



spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      httpclient:
        connectTimeout: 5000
        responseTimeout: 5000
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
           - Path=/users/**
        filters:
          - name: CircuitBreaker
            args:
              name: userCircuitBreaker
              fallbackUri: forward:/userServiceFallback

      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
           - Path=/departments/**
        filters:
          - name: CircuitBreaker
            args:
              name: departmentCircuitBreaker
              fallbackUri: forward:/departmentServiceFallback


  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 350752795641-2megrg15i329ngdt10r07lajidvvr1c2.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile









 

  